-- 코드를 입력하세요
SELECT CAR_ID, MAX(IF(START_DATE <= DATE_FORMAT("2022-10-16", "%Y-%m-%d") AND DATE_FORMAT("2022-10-16", "%Y-%m-%d") <= END_DATE, '대여중', '대여 가능')) as AVALIABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC