SELECT
        YEAR(e.DIFFERENTIATION_DATE) as Y1,
        t.M2 - e.SIZE_OF_COLONY,
        e.ID
    FROM ECOLI_DATA as e
    JOIN
        (SELECT YEAR(DIFFERENTIATION_DATE) as Y2, MAX(SIZE_OF_COLONY) as M2 FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) as t ON YEAR(e.DIFFERENTIATION_DATE) = t.Y2
    ORDER BY Y1, t.M2 - e.SIZE_OF_COLONY